networks:
  public:
    external: true
  private:
    external: true

services:
  app:
    image: ${APP_IMAGE}
    environment:
      APP_DOMAIN: ${APP_DOMAIN}
      APP_SECRET: ${APP_SECRET}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: pgbouncer
    networks:
      - public
      - private
    healthcheck:
      test: ['CMD', 'node', 'scripts/healthcheck.mjs']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      replicas: 3
      update_config:
        order: start-first
        failure_action: rollback
      rollback_config:
        order: start-first
      labels:
        - traefik.enable=true
        - traefik.http.routers.app.rule=Host(`${APP_DOMAIN}`)
        - traefik.http.services.app.loadbalancer.server.port=3000
        - traefik.swarm.lbswarm=true
