networks:
  public:
    external: true
  private:
    external: true

volumes:
  postgres_data:

services:
  pgbouncer:
    image: edoburu/pgbouncer:v1.25.2-p0
    environment:
      DATABASE_URL: postgres://postgres:${DB_PASSWORD}@postgres/postgres
      AUTH_TYPE: scram-sha-256
      POOL_MODE: transaction
      SERVER_LOGIN_RETRY: 1
      SERVER_CONNECT_TIMEOUT: 1
    networks:
      - private
    healthcheck:
      test: ['CMD', 'pg_isready', '-h', 'localhost']
      interval: 2s
      timeout: 2s
      retries: 2
      start_period: 10s
    deploy:
      replicas: 3
      update_config:
        order: start-first
        failure_action: rollback
      rollback_config:
        order: start-first

  postgres:
    image: postgres:18.4
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - private
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 2s
      timeout: 2s
      retries: 2
      start_period: 10s
    deploy:
      update_config:
        failure_action: rollback
      placement:
        constraints:
          - node.role == manager

  traefik:
    image: traefik:v3.7.10
    networks:
      - public
    ports:
      - target: 80
        published: 80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --providers.swarm=true
      - --providers.swarm.exposedbydefault=false
      - --providers.swarm.network=public
      - --entrypoints.web.address=:80
      - --accesslog=true
      - --log.level=info
      - --ping=true
    healthcheck:
      test: ['CMD', 'traefik', 'healthcheck', '--ping']
      interval: 2s
      timeout: 2s
      retries: 2
      start_period: 10s
    deploy:
      replicas: 3
      update_config:
        order: start-first
        failure_action: rollback
      rollback_config:
        order: start-first

  cloudflared:
    image: cloudflare/cloudflared:2026.7.3
    environment:
      TUNNEL_TOKEN: ${TUNNEL_TOKEN}
    networks:
      - public
    command: tunnel --metrics :20241 --no-autoupdate run
    healthcheck:
      test: ['CMD', 'cloudflared', 'tunnel', '--metrics', ':20241', 'ready']
      interval: 2s
      timeout: 2s
      retries: 2
      start_period: 10s
    deploy:
      replicas: 3
      update_config:
        order: start-first
        failure_action: rollback
      rollback_config:
        order: start-first
